name:                advent-of-haskell
version:             0.1.0.0
github:              mgkoning/advent-of-code-2019
license:             BSD3
author:              Michiel Koning
maintainer:          m.g.koning@gmail.com
copyright:           2019 Michiel Koning

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgkoning/advent-of-code-2019#readme>

dependencies:
- base >= 4.7 && < 5
- time
- containers

library:
  source-dirs: src

executables:
  advent-of-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-haskell

tests:
  advent-of-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-haskell
